name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  # This single job handles installing dependencies, generating the static site, and deploying it.
  deploy_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false # Skip initial install here

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Dependencies
        # Using --frozen-lockfile ensures reproducible builds
        run: pnpm install --frozen-lockfile

      - name: Generate Static Site
        # This step runs your "generate" script: "nuxt prepare && nuxt generate www"
        # This command is responsible for generating files into 'www/.output/public'
        env:
          NUXT_APP_BASE_URL: /comforthrmdocsnuxt/ # Setting the BASE_URL environment variable for Nuxt
        run: pnpm run generate

      - name: Deploy to GitHub Pages
        # This action pushes the generated content to the 'gh-pages' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Ensure this path matches the output of 'nuxt generate www'
          publish_dir: www/.output/public
          publish_branch: gh-pages
          # Optional: Add a custom commit message
          commit_message: Deploying static Nuxt site to gh-pages
